[build]
  functions = "dist/functions"
  command = "yarn run build"

[dev]
  publish = "dist"
  command = "yarn run start"
  port = 8888

[context.production]
  command = "ENV=production yarn run build"

[context.branch-deploy]
  command = "ENV=staging yarn run build"

[context.deploy-preview]
  command = "ENV=staging yarn run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
