[build]
  functions = "dist/functions"
  command = "yarn run build"

[dev]
  publish = "dist"
  command = "yarn run start"
  port = 1234

[context.production]
  environment = { ENV = "production" }

[context.branch-deploy]
  environment = { ENV = "staging" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
