[build]
  functions = "dist/functions"
  command = "yarn run build"

[dev]
  publish = "dist"
  command = "yarn run start"
  port = 1234

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
